### PR TITLE
pr/199

### PR DESCRIPTION
**Pull request by 3rd**
https://github.com/3rd/image.nvim/pull/199

### CODE REVIEW

**Comment by maxbol** [comment]
#199 still does not work for me. Doing some quick print debugging on the code it looks like `utils.tmux.get_current_session()` always returns the name of the session where the editor that lost focus lives. So it always is the same as `initial_tmux_session` when losing focus due to switching sessions, and therefore nothing gets cleared. Using tmux 3.4 and Neovim 0.10.1.

EDIT: Ran a quick experiment with `tmux display-message` and it looks like #{session_name} always reports the name of the session that the process is run from. To validate, open a tmux session and run:

```bash
sleep 2 && tmux display-message -p '#{session_name}'
```

And quickly step into another session before the command triggers. It will never pick up any other session name than the name of the session from where the cmd was run.

**Comment by maxbol** [comment]
I believe the correct way to get the pane TTY for deleting the image should be:

```bash
tmux list-panes -t $(tmux display-message -p '#{client_session}') -F '#{pane_tty}' -f '#{pane_active}'
```

**Comment by maxbol** [comment]
See https://github.com/3rd/image.nvim/pull/221

**Comment by 3rd** [comment]
Thank you @maxbol :pray:

**Pull request merged**
