### PR TITLE
feat: handle external source image changes

### PR DESCRIPTION
**Pull request by 3rd**
Related to https://github.com/3rd/image.nvim/pull/150

Preview: https://gist.ro/lastmodified.mp4

### CODE REVIEW

**Comment by jonboh** [comment]
I've tested this a bit, and it seems to work well 👍
I'm going to keep using this branch for some time, I'll come back if I find something next week, thanks!
I'll close https://github.com/3rd/image.nvim/pull/150, in favor of this

**Comment by NikodemMarek** [comment]
hey, any progress on this?

**Comment by 3rd** [comment]
hey, going to go over it to make sure it doesn't break anything and will merge it in a few hours

**Comment by jonboh** [comment]
As far as I tested this branch it seemed to work well, but I'm no longer using it in my day to day. I used this with neorg's latex rendered, but the performance of large documents wasn't good, so I just ended up writting Latex docs

**Pull request merged**
