### PR TITLE
fix(kitty): image shown when switching to different tmux session #198

### LINKED ISSUE #198: Image still shown when switching to a different tmux session
How to reproduce:
1. setup two tmux sessions (not windows)
2. minimal config on first to display image
3. Ctrl+Shift+L to navigate to second
4. image is still displayed
Possibly related to: #106 

tmux 3.4
kitty 0.35.2
nvim v0.10.0
image.nvim 61c76515cfc3cdac8123ece9e9761b20c3dc1315
``` tmux.conf
set -gq allow-passthrough on
set -g visual-activity off
```

### session 'notes'
image
### session 'image_nvim'
image

### PR DESCRIPTION
**Pull request by shurensha**
fixes #198

steps to verify PR on issue above.

Approach:
1. detect and clear image when attached session has changed
2. detect and clear currently active pane tty across sessions

### CODE REVIEW

**Comment by 3rd** [comment]
Hey, thank you for your work, checking it out!
I'll probably merge it into a different branch first to replace the awk/xargs/etc part with Lua, and we can get it in <3

**Comment by 3rd** [comment]
This is a bit problematic with multiple attached sessions, looking into it.

**Comment by 3rd** [comment]
@shurensha I think something like this should work https://github.com/3rd/image.nvim/tree/pr/199
Could you please try it out?

**Comment by maxbol** [comment]
#199 still does not work for me. Doing some quick print debugging on the code it looks like `utils.tmux.get_current_session()` always returns the name of the session where the editor that lost focus lives. So it always is the same as `initial_tmux_session` when losing focus due to switching sessions, and therefore nothing gets cleared. Using tmux 3.4 and Neovim 0.10.1.

**Pull request merged**
